### ISSUE TITLE
There is a better way

### ISSUE THREAD

**Issue by xweis** [im7mortal/kmutex#1]
```go
package main

import (
	"sync"
	"time"
)

var l [3]sync.Mutex

func main() {
	wg := sync.WaitGroup{}

	ids := []string{
		"red",
		"blue",
		"yellow",
	}

	ii := 0
	for i := 0; i < 90; i++ {
		wg.Add(1)
		go func(iii int, i int) {
			l[iii].Lock()
			time.Sleep(time.Second)
			println(i, ids[iii])
			l[iii].Unlock()
			wg.Done()
		}(ii, i)
		ii++
		if ii == 3 {
			ii = 0
		}
	}
	wg.Wait()
}
```

**Comment by im7mortal** [comment]
Hi @xweis !
In your example you assume that there only 3 resources. But in my case there are infinite number of keys.
You can see description of problem which I am solving here: https://www.reddit.com/r/golang/comments/6w37q3/kmutex_lock_part_of_resource_by_unique_id/dm84azo/?context=8&depth=9
